export const autorunInput = [
  {
    startThreshold: 0,
    endThreshold: 200,
    step: 1,
    feeRate: 4.704,
    startDate: '2025-01-01',
    symbol: 'XAUUSD',
    usdPosition: 'quote',
    exchangePrice: 1,
    spread: 10,
  },
  {
    startThreshold: 0,
    endThreshold: 200,
    step: 1,
    feeRate: 4.704,
    startDate: '2024-01-01',
    symbol: 'XAUUSD',
    usdPosition: 'quote',
    exchangePrice: 1,
    spread: 10,
  },
  {
    startThreshold: 0,
    endThreshold: 200,
    step: 1,
    feeRate: 4.704,
    startDate: '2023-01-01',
    symbol: 'XAUUSD',
    usdPosition: 'quote',
    exchangePrice: 1,
    spread: 10,
  },
];
