export const autorunInput = [
  {
    startThreshold: 0,
    endThreshold: 20,
    step: 1,
    feeRate: 4.704,
    startDate: '2025-01-01',
    symbol: 'XAUUSD',
    usdPosition: 'quote',
    exchangePrice: 1,
    spread: 10,
  },
  {
    startThreshold: 0,
    endThreshold: 20,
    step: 1,
    feeRate: 4.704,
    startDate: '2024-01-01',
    symbol: 'XAUUSD',
    usdPosition: 'quote',
    exchangePrice: 1,
    spread: 10,
  },
  {
    startThreshold: 0,
    endThreshold: 20,
    step: 1,
    feeRate: 4.704,
    startDate: '2023-01-01',
    symbol: 'XAUUSD',
    usdPosition: 'quote',
    exchangePrice: 1,
    spread: 10,
  },

  {
    startThreshold: 0,
    endThreshold: 20,
    step: 1,
    feeRate: 2.032,
    symbol: 'GBPUSD',
    startDate: '2025-01-01',
    usdPosition: 'quote',
    exchangePrice: 1,
    spread: 3,
  },
  {
    startThreshold: 0,
    endThreshold: 20,
    step: 1,
    feeRate: 2.032,
    startDate: '2024-01-01',
    symbol: 'GBPUSD',
    usdPosition: 'quote',
    exchangePrice: 1,
    spread: 3,
  },
  {
    startThreshold: 0,
    endThreshold: 20,
    step: 1,
    feeRate: 2.032,
    startDate: '2023-01-01',
    symbol: 'GBPUSD',
    usdPosition: 'quote',
    exchangePrice: 1,
    spread: 3,
  },

  {
    startThreshold: 0,
    endThreshold: 20,
    step: 1,
    feeRate: 1.68,
    symbol: 'EURUSD',
    startDate: '2025-01-01',
    usdPosition: 'quote',
    exchangePrice: 1,
    spread: 1,
  },
  {
    startThreshold: 0,
    endThreshold: 20,
    step: 1,
    feeRate: 1.68,
    symbol: 'EURUSD',
    startDate: '2024-01-01',
    usdPosition: 'quote',
    exchangePrice: 1,
    spread: 1,
  },
  {
    startThreshold: 0,
    endThreshold: 20,
    step: 1,
    feeRate: 1.68,
    symbol: 'EURUSD',
    startDate: '2023-01-01',
    usdPosition: 'quote',
    exchangePrice: 1,
    spread: 1,
  },

  {
    startThreshold: 0,
    endThreshold: 20,
    step: 1,
    feeRate: 1.6,
    symbol: 'USDJPY',
    startDate: '2025-01-01',
    usdPosition: 'base',
    exchangePrice: 1,
    spread: 2,
  },
  {
    startThreshold: 0,
    endThreshold: 20,
    step: 1,
    feeRate: 1.6,
    symbol: 'USDJPY',
    startDate: '2024-01-01',
    usdPosition: 'base',
    exchangePrice: 1,
    spread: 2,
  },
  {
    startThreshold: 0,
    endThreshold: 20,
    step: 1,
    feeRate: 1.6,
    symbol: 'USDJPY',
    startDate: '2023-01-01',
    usdPosition: 'base',
    exchangePrice: 1,
    spread: 2,
  },
  {
    startThreshold: 0,
    endThreshold: 20,
    step: 1,
    feeRate: 2.032,
    startDate: '2025-01-01',
    symbol: 'GBPJPY',
    usdPosition: 'exchange',
    exchangePrice: 149,
    spread: 8,
  },
  {
    startThreshold: 0,
    endThreshold: 20,
    step: 1,
    feeRate: 2.032,
    startDate: '2024-01-01',
    symbol: 'GBPJPY',
    usdPosition: 'exchange',
    exchangePrice: 149,
    spread: 8,
  },
  {
    startThreshold: 0,
    endThreshold: 20,
    step: 1,
    feeRate: 2.032,
    startDate: '2023-01-01',
    symbol: 'GBPJPY',
    usdPosition: 'exchange',
    exchangePrice: 149,
    spread: 8,
  },
];
