// Error Response DTO
export class ErrorResponseDto {
  error_code: string;
  error_message: string;
}

// Common rejection error codes
export enum RejectionReasonCode {
  // Place order rejections
  ACCESS_TO_INSTRUMENT_DENIED = 'ACCESS_TO_INSTRUMENT_DENIED',
  ACCOUNT_DOES_NOT_EXIST = 'ACCOUNT_DOES_NOT_EXIST',
  ACCOUNT_IN_LIQUIDATION = 'ACCOUNT_IN_LIQUIDATION',
  ACCOUNT_SUSPENDED = 'ACCOUNT_SUSPENDED',
  BAD_REQUEST = 'BAD_REQUEST',
  DUPLICATE_ORDER = 'DUPLICATE_ORDER',
  INSTRUCTION_ID_INVALID = 'INSTRUCTION_ID_INVALID',
  INSTRUMENT_NOT_FOUND = 'INSTRUMENT_NOT_FOUND',
  INSTRUMENT_NOT_READY = 'INSTRUMENT_NOT_READY',
  INSTRUMENT_SUSPENDED = 'INSTRUMENT_SUSPENDED',
  INSUFFICIENT_FUNDS = 'INSUFFICIENT_FUNDS',
  MAXIMUM_POSITION_EXCEEDED = 'MAXIMUM_POSITION_EXCEEDED',
  PARSING_ERROR = 'PARSING_ERROR',
  QUANTITY_NOT_A_POSITIVE_NUMBER = 'QUANTITY_NOT_A_POSITIVE_NUMBER',
  QUANTITY_NOT_A_VALID_INCREMENT = 'QUANTITY_NOT_A_VALID_INCREMENT',
  QUANTITY_NOT_A_VALID_NUMBER = 'QUANTITY_NOT_A_VALID_NUMBER',
  QUANTITY_NOT_VALID = 'QUANTITY_NOT_VALID',
  PRICE_NOT_A_POSITIVE_NUMBER = 'PRICE_NOT_A_POSITIVE_NUMBER',
  PRICE_NOT_A_VALID_INCREMENT = 'PRICE_NOT_A_VALID_INCREMENT',
  PRICE_NOT_A_VALID_NUMBER = 'PRICE_NOT_A_VALID_NUMBER',
  PRICE_NOT_VALID = 'PRICE_NOT_VALID',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  OTHER = 'OTHER',
}
